In [1]:
import random
import datetime
import operator
import numpy as np
import pandas as pd
from datetime import date
from datetime import datetime
import matplotlib.pyplot as plt

In [2]:
eventos = pd.read_pickle('C:/Users/lucas/OneDrive - Universidad Nacional de Colombia/PC-GCPDS/Documentos/data/SuperEventos_Criticidad_AguasAbajo.pkl')

In [3]:
for column in eventos.columns:
    print(column)

evento
equipo_ope
tipo_equi_ope
cto_equi_ope
tipo_elemento
inicio
fin
duracion_h
tipo_duracion
causa
CNT_TRAFOS_AFEC
cnt_usus
SAIDI
SAIFI
ASSEMBLY
PHASES
FPARENT
KV
STATE
LINESECTIO
FECHA
LONGITUD
LATITUD
DEP
MUN
OWNER1
TRFTYPE
ELNODE
IMPEDANCE
DATE_FAB
MARCA
TIPO_SUB
GRUPO015
FECHA_ACT
KVA
KV1
ELNODE1
ELNODE2
CONDUCTOR
NEUTRAL
LENGTH
KVNOM
CLASS
TOWNER
MATERIALCONDUCTOR
TIPOCONDUCTOR
CALIBRECONDUCTOR
GUARDACONDUCTOR
NEUTROCONDUCTOR
NEUTRO_SECUNDARIOCONDUCTOR
NIVEL1CONDUCTOR
NIVEL2CONDUCTOR
NIVEL3CONDUCTOR
NIVEL4CONDUCTOR
ACOMETIDACONDUCTOR
NEUTRO
CALIBRENEUTRO
CAPACITY
RESISTANCE
LONGITUD2
LATITUD2
NIVEL_C
VALOR_C
TRAMOS_AGUAS_ABAJO
EQUIPOS_PUNTOS
PUNTOS_POLIGONO
inicio_evento
h0-clouds
h0-precip
h0-pres
h0-rh
h0-slp
h0-solar_rad
h0-temp
h0-uv
h0-vis
h0-wind_gust_spd
h0-wind_spd
h1-clouds
h1-precip
h1-pres
h1-rh
h1-slp
h1-solar_rad
h1-temp
h1-uv
h1-vis
h1-wind_gust_spd
h1-wind_spd
h2-clouds
h2-precip
h2-pres
h2-rh
h2-slp
h2-solar_rad
h2-temp
h2-uv
h2-vis
h2-wind_gust_spd
h2-wind_spd
h3-clouds
h3-precip
h3-pres
h3-rh
h3-slp
h3-solar_rad
h3-temp
h3-uv
h3-vis
h3-wind_gust_spd
h3-wind_spd
h4-clouds
h4-precip
h4-pres
h4-rh
h4-slp
h4-solar_rad
h4-temp
h4-uv
h4-vis
h4-wind_gust_spd
h4-wind_spd
h5-clouds
h5-precip
h5-pres
h5-rh
h5-slp
h5-solar_rad
h5-temp
h5-uv
h5-vis
h5-wind_gust_spd
h5-wind_spd
h6-clouds
h6-precip
h6-pres
h6-rh
h6-slp
h6-solar_rad
h6-temp
h6-uv
h6-vis
h6-wind_gust_spd
h6-wind_spd
h7-clouds
h7-precip
h7-pres
h7-rh
h7-slp
h7-solar_rad
h7-temp
h7-uv
h7-vis
h7-wind_gust_spd
h7-wind_spd
h8-clouds
h8-precip
h8-pres
h8-rh
h8-slp
h8-solar_rad
h8-temp
h8-uv
h8-vis
h8-wind_gust_spd
h8-wind_spd
h9-clouds
h9-precip
h9-pres
h9-rh
h9-slp
h9-solar_rad
h9-temp
h9-uv
h9-vis
h9-wind_gust_spd
h9-wind_spd
h10-clouds
h10-precip
h10-pres
h10-rh
h10-slp
h10-solar_rad
h10-temp
h10-uv
h10-vis
h10-wind_gust_spd
h10-wind_spd
h11-clouds
h11-precip
h11-pres
h11-rh
h11-slp
h11-solar_rad
h11-temp
h11-uv
h11-vis
h11-wind_gust_spd
h11-wind_spd
h12-clouds
h12-precip
h12-pres
h12-rh
h12-slp
h12-solar_rad
h12-temp
h12-uv
h12-vis
h12-wind_gust_spd
h12-wind_spd
h13-clouds
h13-precip
h13-pres
h13-rh
h13-slp
h13-solar_rad
h13-temp
h13-uv
h13-vis
h13-wind_gust_spd
h13-wind_spd
h14-clouds
h14-precip
h14-pres
h14-rh
h14-slp
h14-solar_rad
h14-temp
h14-uv
h14-vis
h14-wind_gust_spd
h14-wind_spd
h15-clouds
h15-precip
h15-pres
h15-rh
h15-slp
h15-solar_rad
h15-temp
h15-uv
h15-vis
h15-wind_gust_spd
h15-wind_spd
h16-clouds
h16-precip
h16-pres
h16-rh
h16-slp
h16-solar_rad
h16-temp
h16-uv
h16-vis
h16-wind_gust_spd
h16-wind_spd
h17-clouds
h17-precip
h17-pres
h17-rh
h17-slp
h17-solar_rad
h17-temp
h17-uv
h17-vis
h17-wind_gust_spd
h17-wind_spd
h18-clouds
h18-precip
h18-pres
h18-rh
h18-slp
h18-solar_rad
h18-temp
h18-uv
h18-vis
h18-wind_gust_spd
h18-wind_spd
h19-clouds
h19-precip
h19-pres
h19-rh
h19-slp
h19-solar_rad
h19-temp
h19-uv
h19-vis
h19-wind_gust_spd
h19-wind_spd
h20-clouds
h20-precip
h20-pres
h20-rh
h20-slp
h20-solar_rad
h20-temp
h20-uv
h20-vis
h20-wind_gust_spd
h20-wind_spd
h21-clouds
h21-precip
h21-pres
h21-rh
h21-slp
h21-solar_rad
h21-temp
h21-uv
h21-vis
h21-wind_gust_spd
h21-wind_spd
h22-clouds
h22-precip
h22-pres
h22-rh
h22-slp
h22-solar_rad
h22-temp
h22-uv
h22-vis
h22-wind_gust_spd
h22-wind_spd
h23-clouds
h23-precip
h23-pres
h23-rh
h23-slp
h23-solar_rad
h23-temp
h23-uv
h23-vis
h23-wind_gust_spd
h23-wind_spd
ORDER_
FECHA_C
ALTITUD_mean
ALTITUD_median
ALTITUD_min
ALTITUD_max
ALTITUD_std
CORRIENTE_mean
CORRIENTE_median
CORRIENTE_min
CORRIENTE_max
CORRIENTE_std
TIPO_1_count
TIPO_2_count
conteo_vegetacion
nombre_comun_mas_frecuente
CODE
TIPO
CLASE
MATERIAL
LONG_APOYO
TIERRA_PIE
VIENTOS

In [6]:
apoyos_1 = apoyos[apoyos['CODE'] == 'B38003']
apoyos_1

,CODE,ASSEMBLY,TOWNER,FECHA,TIPO,CLASE,MATERIAL,LONG_APOYO,TIERRA_PIE,VIENTOS,LONGITUD,LATITUD,DEP,MUN
2080,B38003,AP215V50T,C,2019-01-31,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
47626,B38003,AP215V50T,C,2019-02-28,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
93236,B38003,AP215V50T,C,2019-03-31,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
138910,B38003,AP215V50T,C,2019-04-30,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
184596,B38003,AP215V50T,C,2019-05-31,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925187,B38003,AP215V50T,C,2024-04-30,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
2972331,B38003,AP215V50T,C,2024-05-31,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
3019483,B38003,AP215V50T,C,2024-06-30,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
3066671,B38003,AP215V50T,C,2024-07-31,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES
3113877,B38003,AP215V50T,C,2024-08-31,A,F,Poste metálico,15.0,T,5.0,-75.143751,5.264643,CALDAS,MANZANARES

In [15]:
print(i)

1

## Transformación

In [9]:
# Conversión de tipos de columnas
def convertir_tipos(df):
    conversiones = {
        'evento': 'object',
        'equipo_ope': 'object',
        'tipo_equi_ope': 'object',
        'cto_equi_ope': 'object',
        'tipo_elemento': 'object',
        'inicio': 'datetime64[ns]',
        'fin': 'datetime64[ns]',
        'duracion_h': 'float32',
        'tipo_duracion': 'object',
        'causa': 'object',
        'CNT_TRAFOS_AFEC': 'float32',
        'cnt_usus': 'float32',
        'SAIDI': 'float32',
        'SAIFI': 'float32',
        'ASSEMBLY': 'object',
        'PHASES': 'float16',
        'FPARENT': 'object',
        'KV': 'float16',
        'STATE': 'object',
        'LINESECTIO': 'object',
        'FECHA': 'object',
        'LONGITUD': 'float64',
        'LATITUD': 'float64',
        'DEP': 'object',
        'MUN': 'object',
        'OWNER1': 'object',
        'TRFTYPE': 'object',
        'ELNODE': 'object',
        'IMPEDANCE': 'float16',
        'DATE_FAB': 'object',
        'MARCA': 'object',
        'TIPO_SUB': 'object',
        'GRUPO015': 'float16',
        'FECHA_ACT': 'object',
        'KVA': 'float32',
        'KV1': 'float32',
        'ELNODE1': 'object',
        'ELNODE2': 'object',
        'CONDUCTOR': 'object',
        'NEUTRAL': 'object',
        'LENGTH': 'float16',
        'KVNOM': 'float16',
        'CLASS': 'float32',
        'TOWNER': 'object',
        'MATERIALCONDUCTOR': 'object',
        'TIPOCONDUCTOR': 'object',
        'CALIBRECONDUCTOR': 'object',
        'GUARDACONDUCTOR': 'float32',
        'NEUTROCONDUCTOR': 'float32',
        'NEUTRO_SECUNDARIOCONDUCTOR': 'float32',
        'NIVEL1CONDUCTOR': 'float32',
        'NIVEL2CONDUCTOR': 'float32',
        'NIVEL3CONDUCTOR': 'float32',
        'NIVEL4CONDUCTOR': 'float32',
        'ACOMETIDACONDUCTOR': 'float32',
        'NEUTRO': 'object',
        'CALIBRENEUTRO': 'object',
        'CAPACITY': 'float32',
        'RESISTANCE': 'float32',
        'LONGITUD2': 'float64',
        'LATITUD2': 'float64',
        'NIVEL_C': 'int32',
        'VALOR_C': 'float32',
        'TRAMOS_AGUAS_ABAJO': 'object',
        'EQUIPOS_PUNTOS': 'object',
        'PUNTOS_POLIGONO': 'object',
        'inicio_evento': 'object',
        'h0-clouds': 'float32',
        'h0-precip': 'float32',
        'h0-pres': 'float32',
        'h0-rh': 'float32',
        'h0-slp': 'float32',
        'h0-solar_rad': 'float32',
        'h0-temp': 'float32',
        'h0-uv': 'float32',
        'h0-vis': 'float32',
        'h0-wind_gust_spd': 'float32',
        'h0-wind_spd': 'float32',
        'h1-clouds': 'float32',
        'h1-precip': 'float32',
        'h1-pres': 'float32',
        'h1-rh': 'float32',
        'h1-slp': 'float32',
        'h1-solar_rad': 'float32',
        'h1-temp': 'float32',
        'h1-uv': 'float32',
        'h1-vis': 'float32',
        'h1-wind_gust_spd': 'float32',
        'h1-wind_spd': 'float32',
        'h2-clouds': 'float32',
        'h2-precip': 'float32',
        'h2-pres': 'float32',
        'h2-rh': 'float32',
        'h2-slp': 'float32',
        'h2-solar_rad': 'float32',
        'h2-temp': 'float32',
        'h2-uv': 'float32',
        'h2-vis': 'float32',
        'h2-wind_gust_spd': 'float32',
        'h2-wind_spd': 'float32',
        'h3-clouds': 'float32',
        'h3-precip': 'float32',
        'h3-pres': 'float32',
        'h3-rh': 'float32',
        'h3-slp': 'float32',
        'h3-solar_rad': 'float32',
        'h3-temp': 'float32',
        'h3-uv': 'float32',
        'h3-vis': 'float32',
        'h3-wind_gust_spd': 'float32',
        'h3-wind_spd': 'float32',
        'h4-clouds': 'float32',
        'h4-precip': 'float32',
        'h4-pres': 'float32',
        'h4-rh': 'float32',
        'h4-slp': 'float32',
        'h4-solar_rad': 'float32',
        'h4-temp': 'float32',
        'h4-uv': 'float32',
        'h4-vis': 'float32',
        'h4-wind_gust_spd': 'float32',
        'h4-wind_spd': 'float32',
        'h5-clouds': 'float32',
        'h5-precip': 'float32',
        'h5-pres': 'float32',
        'h5-rh': 'float32',
        'h5-slp': 'float32',
        'h5-solar_rad': 'float32',
        'h5-temp': 'float32',
        'h5-uv': 'float32',
        'h5-vis': 'float32',
        'h5-wind_gust_spd': 'float32',
        'h5-wind_spd': 'float32',
        'h6-clouds': 'float32',
        'h6-precip': 'float32',
        'h6-pres': 'float32',
        'h6-rh': 'float32',
        'h6-slp': 'float32',
        'h6-solar_rad': 'float32',
        'h6-temp': 'float32',
        'h6-uv': 'float32',
        'h6-vis': 'float32',
        'h6-wind_gust_spd': 'float32',
        'h6-wind_spd': 'float32',
        'h7-clouds': 'float32',
        'h7-precip': 'float32',
        'h7-pres': 'float32',
        'h7-rh': 'float32',
        'h7-slp': 'float32',
        'h7-solar_rad': 'float32',
        'h7-temp': 'float32',
        'h7-uv': 'float32',
        'h7-vis': 'float32',
        'h7-wind_gust_spd': 'float32',
        'h7-wind_spd': 'float32',
        'h8-clouds': 'float32',
        'h8-precip': 'float32',
        'h8-pres': 'float32',
        'h8-rh': 'float32',
        'h8-slp': 'float32',
        'h8-solar_rad': 'float32',
        'h8-temp': 'float32',
        'h8-uv': 'float32',
        'h8-vis': 'float32',
        'h8-wind_gust_spd': 'float32',
        'h8-wind_spd': 'float32',
        'h9-clouds': 'float32',
        'h9-precip': 'float32',
        'h9-pres': 'float32',
        'h9-rh': 'float32',
        'h9-slp': 'float32',
        'h9-uv': 'float32',
        'h9-solar_rad': 'float32',
        'h9-temp': 'float32',
        'h9-vis': 'float32',
        'h9-wind_gust_spd': 'float32',
        'h9-wind_spd': 'float32',
        'h10-clouds': 'float32',
        'h10-precip': 'float32',
        'h10-pres': 'float32',
        'h10-rh': 'float32',
        'h10-slp': 'float32',
        'h10-solar_rad': 'float32',
        'h10-temp': 'float32',
        'h10-uv': 'float32',
        'h10-vis': 'float32',
        'h10-wind_gust_spd': 'float32',
        'h10-wind_spd': 'float32',
        'h11-clouds': 'float32',
        'h11-precip': 'float32',
        'h11-pres': 'float32',
        'h11-rh': 'float32',
        'h11-slp': 'float32',
        'h11-solar_rad': 'float32',
        'h11-temp': 'float32',
        'h11-uv': 'float32',
        'h11-vis': 'float32',
        'h11-wind_gust_spd': 'float32',
        'h11-wind_spd': 'float32',
        'h12-clouds': 'float32',
        'h12-precip': 'float32',
        'h12-pres': 'float32',
        'h12-rh': 'float32',
        'h12-slp': 'float32',
        'h12-solar_rad': 'float32',
        'h12-temp': 'float32',
        'h12-uv': 'float32',
        'h12-vis': 'float32',
        'h12-wind_gust_spd': 'float32',
        'h12-wind_spd': 'float32',
        'h13-clouds': 'float32',
        'h13-precip': 'float32',
        'h13-pres': 'float32',
        'h13-rh': 'float32',
        'h13-slp': 'float32',
        'h13-solar_rad': 'float32',
        'h13-temp': 'float32',
        'h13-uv': 'float32',
        'h13-vis': 'float32',
        'h13-wind_gust_spd': 'float32',
        'h13-wind_spd': 'float32',
        'h14-clouds': 'float32',
        'h14-precip': 'float32',
        'h14-pres': 'float32',
        'h14-rh': 'float32',
        'h14-slp': 'float32',
        'h14-solar_rad': 'float32',
        'h14-temp': 'float32',
        'h14-uv': 'float32',
        'h14-vis': 'float32',
        'h14-wind_gust_spd': 'float32',
        'h14-wind_spd': 'float32',
        'h15-clouds': 'float32',
        'h15-precip': 'float32',
        'h15-pres': 'float32',
        'h15-rh': 'float32',
        'h15-slp': 'float32',
        'h15-solar_rad': 'float32',
        'h15-temp': 'float32',
        'h15-uv': 'float32',
        'h15-vis': 'float32',
        'h15-wind_gust_spd': 'float32',
        'h15-wind_spd': 'float32',
        'h16-clouds': 'float32',
        'h16-precip': 'float32',
        'h16-pres': 'float32',
        'h16-rh': 'float32',
        'h16-slp': 'float32',
        'h16-solar_rad': 'float32',
        'h16-temp': 'float32',
        'h16-uv': 'float32',
        'h16-vis': 'float32',
        'h16-wind_gust_spd': 'float32',
        'h16-wind_spd': 'float32',
        'h17-clouds': 'float32',
        'h17-precip': 'float32',
        'h17-pres': 'float32',
        'h17-rh': 'float32',
        'h17-slp': 'float32',
        'h17-solar_rad': 'float32',
        'h17-temp': 'float32',
        'h17-uv': 'float32',
        'h17-vis': 'float32',
        'h17-wind_gust_spd': 'float32',
        'h17-wind_spd': 'float32',
        'h18-clouds': 'float32',
        'h18-precip': 'float32',
        'h18-pres': 'float32',
        'h18-rh': 'float32',
        'h18-slp': 'float32',
        'h18-solar_rad': 'float32',
        'h18-temp': 'float32',
        'h18-uv': 'float32',
        'h18-vis': 'float32',
        'h18-wind_gust_spd': 'float32',
        'h18-wind_spd': 'float32',
        'h19-clouds': 'float32',
        'h19-precip': 'float32',
        'h19-pres': 'float32',
        'h19-rh': 'float32',
        'h19-slp': 'float32',
        'h19-solar_rad': 'float32',
        'h19-temp': 'float32',
        'h19-uv': 'float32',
        'h19-vis': 'float32',
        'h19-wind_gust_spd': 'float32',
        'h19-wind_spd': 'float32',
        'h20-clouds': 'float32',
        'h20-precip': 'float32',
        'h20-pres': 'float32',
        'h20-rh': 'float32',
        'h20-slp': 'float32',
        'h20-solar_rad': 'float32',
        'h20-temp': 'float32',
        'h20-uv': 'float32',
        'h20-vis': 'float32',
        'h20-wind_gust_spd': 'float32',
        'h20-wind_spd': 'float32',
        'h21-clouds': 'float32',
        'h21-precip': 'float32',
        'h21-pres': 'float32',
        'h21-rh': 'float32',
        'h21-slp': 'float32',
        'h21-solar_rad': 'float32',
        'h21-temp': 'float32',
        'h21-uv': 'float32',
        'h21-vis': 'float32',
        'h21-wind_gust_spd': 'float32',
        'h21-wind_spd': 'float32',
        'h22-clouds': 'float32',
        'h22-precip': 'float32',
        'h22-pres': 'float32',
        'h22-rh': 'float32',
        'h22-slp': 'float32',
        'h22-solar_rad': 'float32',
        'h22-temp': 'float32',
        'h22-uv': 'float32',
        'h22-vis': 'float32',
        'h22-wind_gust_spd': 'float32',
        'h22-wind_spd': 'float32',
        'h23-clouds': 'float32',
        'h23-precip': 'float32',
        'h23-pres': 'float32',
        'h23-rh': 'float32',
        'h23-slp': 'float32',
        'h23-solar_rad': 'float32',
        'h23-temp': 'float32',
        'h23-uv': 'float32',
        'h23-vis': 'float32',
        'h23-wind_gust_spd': 'float32',
        'h23-wind_spd': 'float32',
        'ORDER_': 'float32',
        'FECHA_C': 'object',
        'ALTITUD_mean': 'float32',
        'ALTITUD_median': 'float32',
        'ALTITUD_min': 'float32',
        'ALTITUD_max': 'float32',
        'ALTITUD_std': 'float32',
        'CORRIENTE_mean': 'float32',
        'CORRIENTE_median': 'float32',
        'CORRIENTE_min': 'float32',
        'CORRIENTE_max': 'float32',
        'CORRIENTE_std': 'float32',
        'TIPO_1_count': 'float32',
        'TIPO_2_count': 'float32',
        'conteo_vegetacion': 'int64',
        'nombre_comun_mas_frecuente': 'object',
        'CODE': 'object',
        'TIPO': 'object',
        'CLASE': 'object',
        'MATERIAL': 'object',
        'LONG_APOYO': 'object',
        'TIERRA_PIE': 'object',
        'VIENTOS': 'object',
    }

    for columna, tipo in conversiones.items():
        if tipo == 'datetime64[ns]':
            df[columna] = pd.to_datetime(df[columna], errors='coerce')
        else:
            df[columna] = df[columna].astype(tipo, errors='ignore')

    return df

# Cargar archivo y aplicar función
file_path = 'C:/Users/lucas/OneDrive - Universidad Nacional de Colombia/PC-GCPDS/Documentos/data/SuperEventos_Criticidad_AguasAbajo.csv'
eventos = pd.read_csv(file_path, low_memory=False)
eventos = convertir_tipos(eventos)

In [13]:
eventos.to_pickle("C:/Users/lucas/OneDrive - Universidad Nacional de Colombia/PC-GCPDS/Documentos/data/SuperEventos_Criticidad_AguasAbajo.pkl")

## Transformación

In [40]:
df_4 = pd.read_csv("C:/Users/lucas/OneDrive - Universidad Nacional de Colombia/PC-GCPDS/Documentos/data/SuperEventos_Criticidad.csv")
df_4.dtypes

evento             int64
equipo_ope        object
tipo_equi_ope     object
cto_equi_ope      object
tipo_elemento     object
                  ...
RESISTANCE       float64
LONGITUD2        float64
LATITUD2         float64
NIVEL_C            int64
VALOR_C          float64
Length: 63, dtype: object

#### Transformación 1

In [41]:
df_1 = pd.read_pickle("C:/Users/lucas/OneDrive - Universidad Nacional de Colombia/PC-GCPDS/Documentos/data/Eventos_interruptor.pkl")
df_1.dtypes

evento                     object
equipo_ope                 object
tipo_equi_ope              object
cto_equi_ope               object
tipo_elemento              object
inicio             datetime64[ns]
fin                datetime64[ns]
duracion_h                float32
tipo_duracion              object
causa                      object
CNT_TRAFOS_AFEC           float32
cnt_usus                  float32
SAIDI                     float32
SAIFI                     float32
ASSEMBLY                   object
PHASES                    float32
FPARENT                    object
KV                        float32
STATE                      object
LINESECTIO                 object
FECHA                   period[M]
LONGITUD                  float64
LATITUD                   float64
DEP                        object
MUN                        object
dtype: object

In [42]:
# Convertir columnas al tipo de dato correspondiente
df_4 = df_4.astype({
    "evento": "object",
    "equipo_ope": "object",
    "tipo_equi_ope": "object",
    "cto_equi_ope": "object",
    "tipo_elemento": "object",
    "tipo_duracion": "object",
    "causa": "object",
    "ASSEMBLY": "object",
    "FPARENT": "object",
    "STATE": "object",
    "LINESECTIO": "object",
    "DEP": "object",
    "MUN": "object"
})

# Convertir columnas de fecha a datetime
df_4["inicio"] = pd.to_datetime(df_4["inicio"])
df_4["fin"] = pd.to_datetime(df_4["fin"])

# Convertir duraciones y métricas numéricas a float32
df_4 = df_4.astype({
    "duracion_h": "float32",
    "CNT_TRAFOS_AFEC": "float32",
    "cnt_usus": "float32",
    "SAIDI": "float32",
    "SAIFI": "float32",
    "PHASES": "float32",
    "KV": "float32"
})

# Convertir columna de fecha a un período mensual
df_4["FECHA"] = pd.to_datetime(df_4["FECHA"]).dt.to_period("M")

# Convertir coordenadas geográficas a float64 (si no lo están ya)
df_4 = df_4.astype({
    "LONGITUD": "float64",
    "LATITUD": "float64"
})

#### Transformación 2

In [43]:
df_2 = pd.read_pickle("C:/Users/lucas/OneDrive - Universidad Nacional de Colombia/PC-GCPDS/Documentos/data/Eventos_tramo_linea.pkl")
df_2.dtypes

evento                                object
equipo_ope                            object
tipo_equi_ope                         object
cto_equi_ope                          object
tipo_elemento                         object
inicio                        datetime64[ns]
fin                           datetime64[ns]
duracion_h                           float32
tipo_duracion                         object
causa                                 object
CNT_TRAFOS_AFEC                      float32
cnt_usus                             float32
SAIDI                                float32
SAIFI                                float32
PHASES                               float32
FPARENT                               object
ELNODE1                               object
ELNODE2                               object
CONDUCTOR                             object
NEUTRAL                               object
LENGTH                               float64
KVNOM                                 object
CLASS                                 object
TOWNER                                object
FECHA                              period[M]
MATERIALCONDUCTOR                     object
TIPOCONDUCTOR                         object
CALIBRECONDUCTOR                      object
GUARDACONDUCTOR                       object
NEUTROCONDUCTOR                       object
NEUTRO_SECUNDARIOCONDUCTOR            object
NIVEL1CONDUCTOR                       object
NIVEL2CONDUCTOR                       object
NIVEL3CONDUCTOR                       object
NIVEL4CONDUCTOR                       object
ACOMETIDACONDUCTOR                    object
NEUTRO                                object
CALIBRENEUTRO                         object
FECHA_ACT                          period[M]
CAPACITY                             float32
RESISTANCE                           float32
LONGITUD                             float64
LATITUD                              float64
LONGITUD2                            float64
LATITUD2                             float64
DEP                                   object
MUN                                   object
dtype: object

In [45]:
# Configurar los tipos de dato
df_4 = df_4.astype({
    "evento": "object",
    "equipo_ope": "object",
    "tipo_equi_ope": "object",
    "cto_equi_ope": "object",
    "tipo_elemento": "object",
    "tipo_duracion": "object",
    "causa": "object",
    "FPARENT": "object",
    "ELNODE1": "object",
    "ELNODE2": "object",
    "CONDUCTOR": "object",
    "NEUTRAL": "object",
    "KVNOM": "object",
    "CLASS": "object",
    "TOWNER": "object",
    "MATERIALCONDUCTOR": "object",
    "TIPOCONDUCTOR": "object",
    "CALIBRECONDUCTOR": "object",
    "GUARDACONDUCTOR": "object",
    "NEUTROCONDUCTOR": "object",
    "NEUTRO_SECUNDARIOCONDUCTOR": "object",
    "NIVEL1CONDUCTOR": "object",
    "NIVEL2CONDUCTOR": "object",
    "NIVEL3CONDUCTOR": "object",
    "NIVEL4CONDUCTOR": "object",
    "ACOMETIDACONDUCTOR": "object",
    "NEUTRO": "object",
    "CALIBRENEUTRO": "object",
    "DEP": "object",
    "MUN": "object"
})

# Convertir columnas de fecha a datetime
df_4["inicio"] = pd.to_datetime(df_4["inicio"])
df_4["fin"] = pd.to_datetime(df_4["fin"])

# Convertir columnas de fecha a periodos mensuales
#df_4["FECHA"] = pd.to_datetime(df_4["FECHA"]).dt.to_period("M")
df_4["FECHA_ACT"] = pd.to_datetime(df_4["FECHA_ACT"], errors='coerce').dt.normalize()

# Convertir duraciones y métricas numéricas a float32
df_4 = df_4.astype({
    "duracion_h": "float32",
    "CNT_TRAFOS_AFEC": "float32",
    "cnt_usus": "float32",
    "SAIDI": "float32",
    "SAIFI": "float32",
    "PHASES": "float32",
    "CAPACITY": "float32",
    "RESISTANCE": "float32"
})

# Convertir coordenadas geográficas y longitudes a float64
df_4 = df_4.astype({
    "LONGITUD": "float64",
    "LATITUD": "float64",
    "LONGITUD2": "float64",
    "LATITUD2": "float64"
})

#### Transformación 3

In [46]:
df_3 = pd.read_pickle("C:/Users/lucas/OneDrive - Universidad Nacional de Colombia/PC-GCPDS/Documentos/data/Eventos_transformador.pkl")
df_3.dtypes

evento                     object
equipo_ope                 object
tipo_equi_ope              object
cto_equi_ope               object
tipo_elemento              object
inicio             datetime64[ns]
fin                datetime64[ns]
duracion_h                float32
tipo_duracion              object
causa                      object
CNT_TRAFOS_AFEC           float32
cnt_usus                  float32
SAIDI                     float32
SAIFI                     float32
PHASES                    float32
FPARENT                    object
OWNER1                     object
TRFTYPE                    object
ELNODE                     object
IMPEDANCE                 float32
DATE_FAB                   object
MARCA                      object
TIPO_SUB                   object
FECHA                   period[M]
GRUPO015                  float32
FECHA_ACT               period[M]
KVA                       float32
KV1                       float32
LONGITUD                  float64
LATITUD                   float64
DEP                        object
MUN                        object
dtype: object

In [47]:
# Configurar los tipos de dato
df_4 = df_4.astype({
    "evento": "object",
    "equipo_ope": "object",
    "tipo_equi_ope": "object",
    "cto_equi_ope": "object",
    "tipo_elemento": "object",
    "tipo_duracion": "object",
    "causa": "object",
    "FPARENT": "object",
    "OWNER1": "object",
    "TRFTYPE": "object",
    "ELNODE": "object",
    "DATE_FAB": "object",
    "MARCA": "object",
    "TIPO_SUB": "object",
    "DEP": "object",
    "MUN": "object"
})

# Convertir columnas de fecha a datetime
df_4["inicio"] = pd.to_datetime(df_4["inicio"])
df_4["fin"] = pd.to_datetime(df_4["fin"])

# Convertir columnas de fecha a periodos mensuales
#df_4["FECHA"] = pd.to_datetime(df_4["FECHA"]).dt.to_period("M")
#df_4["FECHA_ACT"] = pd.to_datetime(df_4["FECHA_ACT"]).dt.to_period("M")
df_4["DATE_FAB"] = pd.to_datetime(df_4["DATE_FAB"], errors='coerce').dt.normalize()

# Convertir métricas numéricas a float32
df_4 = df_4.astype({
    "duracion_h": "float32",
    "CNT_TRAFOS_AFEC": "float32",
    "cnt_usus": "float32",
    "SAIDI": "float32",
    "SAIFI": "float32",
    "PHASES": "float32",
    "IMPEDANCE": "float32",
    "GRUPO015": "float32",
    "KVA": "float32",
    "KV1": "float32",
    "NIVEL_C": "int16",
    "VALOR_C": "float32"
})

# Convertir coordenadas geográficas a float64
df_4 = df_4.astype({
    "LONGITUD": "float64",
    "LATITUD": "float64"
})

In [48]:
for column in df_4.columns:
    print(f"{column}           {df_4[column].dtype}")

evento           object
equipo_ope           object
tipo_equi_ope           object
cto_equi_ope           object
tipo_elemento           object
inicio           datetime64[ns]
fin           datetime64[ns]
duracion_h           float32
tipo_duracion           object
causa           object
CNT_TRAFOS_AFEC           float32
cnt_usus           float32
SAIDI           float32
SAIFI           float32
ASSEMBLY           object
PHASES           float32
FPARENT           object
KV           float32
STATE           object
LINESECTIO           object
FECHA           period[M]
LONGITUD           float64
LATITUD           float64
DEP           object
MUN           object
OWNER1           object
TRFTYPE           object
ELNODE           object
IMPEDANCE           float32
DATE_FAB           datetime64[ns]
MARCA           object
TIPO_SUB           object
GRUPO015           float32
FECHA_ACT           datetime64[ns]
KVA           float32
KV1           float32
ELNODE1           object
ELNODE2           object
CONDUCTOR           object
NEUTRAL           object
LENGTH           float64
KVNOM           object
CLASS           object
TOWNER           object
MATERIALCONDUCTOR           object
TIPOCONDUCTOR           object
CALIBRECONDUCTOR           object
GUARDACONDUCTOR           object
NEUTROCONDUCTOR           object
NEUTRO_SECUNDARIOCONDUCTOR           object
NIVEL1CONDUCTOR           object
NIVEL2CONDUCTOR           object
NIVEL3CONDUCTOR           object
NIVEL4CONDUCTOR           object
ACOMETIDACONDUCTOR           object
NEUTRO           object
CALIBRENEUTRO           object
CAPACITY           float32
RESISTANCE           float32
LONGITUD2           float64
LATITUD2           float64
NIVEL_C           int16
VALOR_C           float32

In [56]:
df_4.to_pickle("C:/Users/lucas/OneDrive - Universidad Nacional de Colombia/PC-GCPDS/Documentos/data/SuperEventos.pkl")

In [62]:
df_4.NIVEL_C

0         0
1         1
2         1
3         1
4         2
         ..
168720    1
168721    1
168722    0
168723    0
168724    0
Name: NIVEL_C, Length: 168725, dtype: int16

In [67]:
df_4[['inicio','MUN']]

                    inicio         MUN
0      2019-01-01 00:00:01  MANZANARES
1      2019-01-01 00:00:01  MANZANARES
2      2019-01-01 00:00:01  MANZANARES
3      2019-01-01 00:00:01  MANZANARES
4      2019-01-01 00:00:01  MANZANARES
...                    ...         ...
168720 2024-06-30 18:17:03  VILLAMARÍA
168721 2024-06-30 18:17:40  VILLAMARÍA
168722 2024-06-30 23:11:25    SAN JOSÉ
168723 2024-06-30 23:11:25    SAN JOSÉ
168724 2024-06-30 23:38:56        APÍA

[168725 rows x 2 columns]